### PR TITLE
Add specific examples to brand kit 

### PR DESCRIPTION
**Pull request by pmohun**
Provides some concrete examples to help developers clearly articulate concepts within brand kit.

### CODE REVIEW

**Review by jessepollak — COMMENTED** [review]
Drew - I left a few comments on how I might right the specific examples, but I leave final thoughts up to you.

**Review by T-Damer — COMMENTED** [review]
I think we also need examples in `## Tone and Voice` secion :)

**Comment by jessepollak** [comment]
+1 on including examples in the tone of voice section as well

**Comment by wbnns** [comment]
@pmohun Since some time has passed without further update, we're going to close this PR for now. If you're interested in pursuing these changes in the new year, please let us know and we can reopen. 👍

**Pull request closed without merging**
